// <auto-generated />
using System;
using GrooveOn.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrooveOn.Services.Migrations
{
    [DbContext(typeof(GrooveOnDbContext))]
    [Migration("20260310161631_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrooveOn.Services.Database.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalAlbumId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalArtistId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalGenreId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.ListeningHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayedSeconds")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("ListeningHistories");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.PlaylistSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistSongs");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Administrator sistema",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Standardni korisnik aplikacije",
                            IsActive = true,
                            Name = "Korisnik"
                        });
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ExternalTrackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("PaymentAmount")
                        .HasColumnType("real");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Osnovni plan sa preview pristupom",
                            DurationDays = 0,
                            IsActive = true,
                            Name = "Free",
                            Price = 0f
                        },
                        new
                        {
                            Id = 2,
                            Description = "Premium plan za 30 dana",
                            DurationDays = 30,
                            IsActive = true,
                            Name = "Premium",
                            Price = 4.99f
                        },
                        new
                        {
                            Id = 3,
                            Description = "Napredni plan za 30 dana",
                            DurationDays = 30,
                            IsActive = true,
                            Name = "Premium Plus",
                            Price = 9.99f
                        });
                });

            modelBuilder.Entity("GrooveOn.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "N5j2eDQUE5RjvDf3U6+4bfx3NWw9ul/FoSXjpV+rIXea3HUd6VD+YOgoxlgYM+3E1vXnfcrH8fReRDpTDQmhqA==",
                            PasswordSalt = "m5bvolwO3KB9dHeODWBZHr5HYlhh5zfTvtj3hRmI463gqewdXgfeTc958AMHq7sPJSA7UeROTP7LRMDNse4O8ZkZ70mtrAbou/aX1K+BuM6CZPDR0M3WSPUnEvCMquxkHr7FVD1KzJDtyacRTWjgXaJmYA4ZEO4Fx9RCqkdZqPc=",
                            PhoneNumber = "061111111",
                            Username = "admin123"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1998, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin2@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "N5j2eDQUE5RjvDf3U6+4bfx3NWw9ul/FoSXjpV+rIXea3HUd6VD+YOgoxlgYM+3E1vXnfcrH8fReRDpTDQmhqA==",
                            PasswordSalt = "m5bvolwO3KB9dHeODWBZHr5HYlhh5zfTvtj3hRmI463gqewdXgfeTc958AMHq7sPJSA7UeROTP7LRMDNse4O8ZkZ70mtrAbou/aX1K+BuM6CZPDR0M3WSPUnEvCMquxkHr7FVD1KzJDtyacRTWjgXaJmYA4ZEO4Fx9RCqkdZqPc=",
                            PhoneNumber = "061111112",
                            Username = "admin456"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2002, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user1@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "+ey4BLLFZcx8KGhwLSWmKDwMStixJDVDhtgX2DmA/N0UUd35BCzjj8/nlNMrJimHQJ4CT5RkT9qPf/Qmz0hIZw==",
                            PasswordSalt = "GX/ecg+UvvKwUEcZF9D3YxzIuU4SsSJ7CTqp4ZzOVNr9oem5SeKztYyzbJOA/if6Arh2/9pMtApP6WY/XjJKag5QfnZdM/cMfU5G4DCfzGjXYWDmSvBDuRILrrJdTqaFtgnP8U7CRdhYm+tK36OIbhJ1qR+q3Al3QoD1m4hxGD4=",
                            PhoneNumber = "061111113",
                            Username = "user1234"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1999, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "+ey4BLLFZcx8KGhwLSWmKDwMStixJDVDhtgX2DmA/N0UUd35BCzjj8/nlNMrJimHQJ4CT5RkT9qPf/Qmz0hIZw==",
                            PasswordSalt = "GX/ecg+UvvKwUEcZF9D3YxzIuU4SsSJ7CTqp4ZzOVNr9oem5SeKztYyzbJOA/if6Arh2/9pMtApP6WY/XjJKag5QfnZdM/cMfU5G4DCfzGjXYWDmSvBDuRILrrJdTqaFtgnP8U7CRdhYm+tK36OIbhJ1qR+q3Al3QoD1m4hxGD4=",
                            PhoneNumber = "061111114",
                            Username = "music2026"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2001, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user3@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "+ey4BLLFZcx8KGhwLSWmKDwMStixJDVDhtgX2DmA/N0UUd35BCzjj8/nlNMrJimHQJ4CT5RkT9qPf/Qmz0hIZw==",
                            PasswordSalt = "GX/ecg+UvvKwUEcZF9D3YxzIuU4SsSJ7CTqp4ZzOVNr9oem5SeKztYyzbJOA/if6Arh2/9pMtApP6WY/XjJKag5QfnZdM/cMfU5G4DCfzGjXYWDmSvBDuRILrrJdTqaFtgnP8U7CRdhYm+tK36OIbhJ1qR+q3Al3QoD1m4hxGD4=",
                            PhoneNumber = "061111115",
                            Username = "groove789"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2003, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user4@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "+ey4BLLFZcx8KGhwLSWmKDwMStixJDVDhtgX2DmA/N0UUd35BCzjj8/nlNMrJimHQJ4CT5RkT9qPf/Qmz0hIZw==",
                            PasswordSalt = "GX/ecg+UvvKwUEcZF9D3YxzIuU4SsSJ7CTqp4ZzOVNr9oem5SeKztYyzbJOA/if6Arh2/9pMtApP6WY/XjJKag5QfnZdM/cMfU5G4DCfzGjXYWDmSvBDuRILrrJdTqaFtgnP8U7CRdhYm+tK36OIbhJ1qR+q3Al3QoD1m4hxGD4=",
                            PhoneNumber = "061111116",
                            Username = "playlist1"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1997, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user5@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "+ey4BLLFZcx8KGhwLSWmKDwMStixJDVDhtgX2DmA/N0UUd35BCzjj8/nlNMrJimHQJ4CT5RkT9qPf/Qmz0hIZw==",
                            PasswordSalt = "GX/ecg+UvvKwUEcZF9D3YxzIuU4SsSJ7CTqp4ZzOVNr9oem5SeKztYyzbJOA/if6Arh2/9pMtApP6WY/XjJKag5QfnZdM/cMfU5G4DCfzGjXYWDmSvBDuRILrrJdTqaFtgnP8U7CRdhYm+tK36OIbhJ1qR+q3Al3QoD1m4hxGD4=",
                            PhoneNumber = "061111117",
                            Username = "album2025"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1996, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user6@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "+ey4BLLFZcx8KGhwLSWmKDwMStixJDVDhtgX2DmA/N0UUd35BCzjj8/nlNMrJimHQJ4CT5RkT9qPf/Qmz0hIZw==",
                            PasswordSalt = "GX/ecg+UvvKwUEcZF9D3YxzIuU4SsSJ7CTqp4ZzOVNr9oem5SeKztYyzbJOA/if6Arh2/9pMtApP6WY/XjJKag5QfnZdM/cMfU5G4DCfzGjXYWDmSvBDuRILrrJdTqaFtgnP8U7CRdhYm+tK36OIbhJ1qR+q3Al3QoD1m4hxGD4=",
                            PhoneNumber = "061111118",
                            Username = "rockstar9"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2004, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user7@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "+ey4BLLFZcx8KGhwLSWmKDwMStixJDVDhtgX2DmA/N0UUd35BCzjj8/nlNMrJimHQJ4CT5RkT9qPf/Qmz0hIZw==",
                            PasswordSalt = "GX/ecg+UvvKwUEcZF9D3YxzIuU4SsSJ7CTqp4ZzOVNr9oem5SeKztYyzbJOA/if6Arh2/9pMtApP6WY/XjJKag5QfnZdM/cMfU5G4DCfzGjXYWDmSvBDuRILrrJdTqaFtgnP8U7CRdhYm+tK36OIbhJ1qR+q3Al3QoD1m4hxGD4=",
                            PhoneNumber = "061111119",
                            Username = "indie2024"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2000, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user8@grooveon.com",
                            FirstName = "",
                            IsActive = true,
                            JoinDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Password = "",
                            PasswordHash = "+ey4BLLFZcx8KGhwLSWmKDwMStixJDVDhtgX2DmA/N0UUd35BCzjj8/nlNMrJimHQJ4CT5RkT9qPf/Qmz0hIZw==",
                            PasswordSalt = "GX/ecg+UvvKwUEcZF9D3YxzIuU4SsSJ7CTqp4ZzOVNr9oem5SeKztYyzbJOA/if6Arh2/9pMtApP6WY/XjJKag5QfnZdM/cMfU5G4DCfzGjXYWDmSvBDuRILrrJdTqaFtgnP8U7CRdhYm+tK36OIbhJ1qR+q3Al3QoD1m4hxGD4=",
                            PhoneNumber = "061111120",
                            Username = "listener8"
                        });
                });

            modelBuilder.Entity("GrooveOn.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateAssigned = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Album", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Favorite", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.Song", "Song")
                        .WithMany("Favorites")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrooveOn.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.ListeningHistory", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.Song", "Song")
                        .WithMany("ListeningHistories")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrooveOn.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Playlist", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.PlaylistSong", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrooveOn.Services.Database.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Question", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Song", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId");

                    b.HasOne("GrooveOn.Services.Database.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrooveOn.Services.Database.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("GenreId");

                    b.Navigation("Album");

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Subscription", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrooveOn.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.UserRole", b =>
                {
                    b.HasOne("GrooveOn.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrooveOn.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.Song", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("ListeningHistories");

                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("GrooveOn.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
