# --------------------
# BASE STAGE
# --------------------
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

# --------------------
# BUILD STAGE
# --------------------
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Kopiraj sve csproj fajlove i restore (ukljucujuci project reference fajlove)
COPY ["GrooveOn.WebAPI/GrooveOn.WebAPI.csproj", "GrooveOn.WebAPI/"]
COPY ["GrooveOn.Models/GrooveOn.Models.csproj", "GrooveOn.Models/"]
COPY ["GrooveOn.Services/GrooveOn.Services.csproj", "GrooveOn.Services/"]
COPY ["GrooveOn.MailingService/GrooveOn.MailingService.csproj", "GrooveOn.MailingService/"]
RUN dotnet restore "GrooveOn.WebAPI/GrooveOn.WebAPI.csproj"

# Kopiraj sve i publish
COPY . .
WORKDIR "/src/GrooveOn.WebAPI"
RUN dotnet publish "GrooveOn.WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# --------------------
# FINAL STAGE
# --------------------
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "GrooveOn.WebAPI.dll"]