# --------------------
# BASE STAGE
# --------------------
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

# --------------------
# BUILD STAGE
# --------------------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Kopiraj csproj i restore
COPY ["GrooveOn.WebAPI/GrooveOn.WebAPI.csproj", "GrooveOn.WebAPI/"]
RUN dotnet restore "GrooveOn.WebAPI/GrooveOn.WebAPI.csproj"

# Kopiraj sve i publish
COPY . .
WORKDIR "/src/GrooveOn.WebAPI"
RUN dotnet publish "GrooveOn.WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# --------------------
# FINAL STAGE
# --------------------
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "GrooveOn.WebAPI.dll"]