# --------------------
# BUILD STAGE
# --------------------
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
WORKDIR /src

# Kopiraj csproj i restore
COPY GrooveOn.MailingService/GrooveOn.MailingService.csproj GrooveOn.MailingService/
RUN dotnet restore GrooveOn.MailingService/GrooveOn.MailingService.csproj

# Kopiraj sve i publish
COPY . .
WORKDIR /src/GrooveOn.MailingService
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# --------------------
# RUNTIME STAGE
# --------------------
FROM mcr.microsoft.com/dotnet/runtime:9.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "GrooveOn.MailingService.dll"]